{% set version = '2.1-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dmm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dmm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dmm/dmm_{{ version }}.tar.gz
  sha256: eab0b144f52b5b7fe2b4aa99013a412ec4e91afbb5d5e4ef8eda8bc09e5e24c5

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-matrix
    - r-nadiv
    - r-pls
    - r-robustbase

  run:
    - r-base
    - r-mass
    - r-matrix
    - r-nadiv
    - r-pls
    - r-robustbase

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dmm')"           # [not win]
    - "\"%R%\" -e \"library('dmm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=dmm
  license: GPL-2 | GPL-2 | GPL-3
  summary: Dyadic mixed model analysis with multi-trait responses and pedigree-based partitioning
    of individual variation into a range of environmental and genetic variance components
    for individual and maternal effects.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: dmm
# Type: Package
# Title: Dyadic Mixed Model for Pedigree Data
# Version: 2.1-5
# Date: 2018-07-16
# Author: Neville Jackson
# Maintainer: Neville Jackson <nanddjackson@bigpond.com>
# Description: Dyadic mixed model analysis with multi-trait responses and pedigree-based partitioning of individual variation into a range of environmental and genetic variance components for individual and maternal effects.
# Depends: MASS, Matrix, nadiv, robustbase, pls
# Imports: stats, graphics, grDevices
# License: GPL-2 | GPL (>= 2) | GPL-3
# NeedsCompilation: no
# Packaged: 2018-07-16 07:11:31 UTC; nevj
# Repository: CRAN
# Date/Publication: 2018-07-16 08:00:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
