{% set name = "NaiveDE" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: 'https://github.com/Teichlab/{{ name }}.git'
  git_rev: 'master'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - scipy
    - tqdm
    - patsy
    - matplotlib
  run:
    - numpy
    - pandas
    - python
    - scipy
    - tqdm
    - patsy
    - matplotlib

test:
  imports:
    - NaiveDE

about:
  home: https://github.com/Teichlab/NaiveDE/tree/master/NaiveDE
  license: MIT
  license_family: MIT
  license_file:
  summary: "The most trivial DE test based on likelihood ratio tests"
