{% set version = "3.11.4" %}
{% set name = "org.Hs.eg.db" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: DBI, annotate, RUnit
requirements:
  host:
    - r-base
    - r-runit
    - r-dbi
    - 'bioconductor-annotationdbi'
    - 'bioconductor-annotate'
  run:
    - r-base
    - r-runit
    - r-dbi
    - 'bioconductor-annotationdbi'
    - 'bioconductor-annotate'
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Genome wide annotation for Human'
  description: 'Genome wide annotation for Human, primarily based on mapping using Entrez Gene identifiers.'
