{% set name = "solo-sc" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 04198c6a1cdd5e607fb878ae8fd2e79fa90b13a5f383213e0a0d1c0cf9c834ef

build:
  number: 0
  entry_points:
    - solo=solo.solo:main
    - hashsolo=solo.hashsolo:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - configargparse ==0.14.0
    - cycler ==0.10.0
    - dataclasses ==0.6
    - decorator ==4.4.0
    - h5py ==2.9.0
    - joblib ==0.13.2
    - leidenalg ==0.7.0
    - mock ==3.0.5
    - natsort ==6.0.0
    - networkx ==2.2
    - numba ==0.45.0
    - numexpr ==2.6.9
    - numpy >=1.16.4
    - pandas ==0.24.2
    - patsy ==0.5.1
    - pip
    - prompt-toolkit ==3.0.5
    - pyparsing ==2.4.0
    - pytest ==5.2.1
    - python
    - python-dateutil ==2.8.0
    - pytz ==2019.1
    - scikit-learn ==0.19.1
    - scvi ==0.4.1
    - seaborn ==0.9.0
    - six ==1.12.0
    - statsmodels ==0.9.0
    - pytables ==3.5.1
    - pytorch ==1.0.1
    - tqdm ==4.32.1
    - umap-learn ==0.3.8
  run:
    - configargparse ==0.14.0
    - cycler ==0.10.0
    - dataclasses ==0.6
    - decorator ==4.4.0
    - h5py ==2.9.0
    - joblib ==0.13.2
    - leidenalg ==0.7.0
    - mock ==3.0.5
    - natsort ==6.0.0
    - networkx ==2.2
    - numba ==0.45.0
    - numexpr ==2.6.9
    - numpy >=1.16.4
    - pandas ==0.24.2
    - patsy ==0.5.1
    - prompt-toolkit ==3.0.5
    - pyparsing ==2.4.0
    - pytest ==5.2.1
    - python
    - python-dateutil ==2.8.0
    - pytz ==2019.1
    - scikit-learn ==0.19.1
    - scvi ==0.4.1
    - seaborn ==0.9.0
    - six ==1.12.0
    - statsmodels ==0.9.0
    - pytables ==3.5.1
    - pytorch ==1.0.1
    - tqdm ==4.32.1
    - umap-learn ==0.3.8

test:
  imports:
    - solo
  commands:
    - solo --help
    - hashsolo --help

about:
  home: "http://github.com/calico/solo"
  license: Apache
  license_family: APACHE
  summary: "Neural network classifiers for doublets"
