{% set version = '0.7-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dirichletreg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DirichletReg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DirichletReg/DirichletReg_{{ version }}.tar.gz
  sha256: 57ffbbe1594fecbbce22aa4298c00025650c1ea1b434772e5eb62059074b2880

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rgl, knitr, formatR, testthat
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-formula
    - r-maxlik

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-formula
    - r-maxlik

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DirichletReg')"           # [not win]
    - "\"%R%\" -e \"library('DirichletReg')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/maiermarco/DirichletReg https://CRAN.R-project.org/package=DirichletReg

  license: GPL-2
  summary: Implements Dirichlet regression models in R.

  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: DirichletReg
# Type: Package
# Version: 0.7-0
# Date: 2020-05-28
# Title: Dirichlet Regression in R
# Description: Implements Dirichlet regression models in R.
# Authors@R: person(given  = c("Marco", "Johannes"), family = "Maier", email  = "marco_maier@posteo.de", role   = c("cre", "aut"), comment = c(ORCID = "0000-0002-1715-7456"))
# Encoding: UTF-8
# Depends: R (>= 3.0.0), Formula
# Imports: stats, graphics, methods, maxLik
# Suggests: rgl, knitr, formatR, testthat
# License: GPL (>= 2)
# URL: https://github.com/maiermarco/DirichletReg https://CRAN.R-project.org/package=DirichletReg
# ByteCompile: yes
# LazyLoad: yes
# LazyData: yes
# ZipData: yes
# VignetteBuilder: knitr
# Author: Marco Johannes Maier [cre, aut] (<https://orcid.org/0000-0002-1715-7456>)
# Maintainer: Marco Johannes Maier <marco_maier@posteo.de>
# Repository: CRAN
# Repository/R-Forge/Project: dirichletreg
# Repository/R-Forge/Revision: 32
# Repository/R-Forge/DateTimeStamp: 2020-05-28 18:49:22
# Date/Publication: 2020-05-29 12:30:14 UTC
# NeedsCompilation: yes
# Packaged: 2020-05-28 19:13:07 UTC; rforge

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
